# Generated by Django 5.2.8 on 2025-11-22 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام برند')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='آدرس سئو (slug)')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان آگهی')),
                ('model', models.CharField(max_length=100, verbose_name='مدل')),
                ('year', models.PositiveIntegerField(verbose_name='سال تولید')),
                ('mileage', models.PositiveIntegerField(verbose_name='کارکرد (کیلومتر)')),
                ('gear_type', models.CharField(choices=[('manual', 'دنده\u200cای'), ('auto', 'اتومات')], max_length=10, verbose_name='نوع گیربکس')),
                ('fuel_type', models.CharField(choices=[('benzin', 'بنزین'), ('gas', 'گاز'), ('hybrid', 'هیبرید'), ('diesel', 'دیزل')], default='benzin', max_length=10, verbose_name='نوع سوخت')),
                ('body_status', models.CharField(blank=True, max_length=200, verbose_name='وضعیت بدنه (بدون رنگ، دو تکه رنگ و ...)')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='رنگ بدنه')),
                ('price', models.BigIntegerField(blank=True, null=True, verbose_name='قیمت (تومان)')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات فروشنده / توضیحات خودرو')),
                ('main_image', models.ImageField(upload_to='cars/', verbose_name='عکس اصلی خودرو')),
                ('is_active', models.BooleanField(default=True, verbose_name='نمایش در سایت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='خودرو ویژه (نمایش در صفحه اصلی)')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='آدرس سئو (slug) برای صفحه خودرو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='core.brand', verbose_name='برند')),
            ],
            options={
                'verbose_name': 'خودرو',
                'verbose_name_plural': 'خودروها',
                'ordering': ('-created_at',),
            },
        ),
    ]
