# Generated by Django 5.2.8 on 2025-11-23 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان دسته')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='آدرس سئو (slug) دسته')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='نام آپشن')),
            ],
            options={
                'verbose_name': 'آپشن',
                'verbose_name_plural': 'آپشن\u200cها',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='عنوان تگ')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='آدرس سئو (slug) تگ')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='car',
            name='has_accident',
            field=models.BooleanField(default=False, verbose_name='سابقه تصادف'),
        ),
        migrations.AddField(
            model_name='car',
            name='insurance_valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='اعتبار بیمه'),
        ),
        migrations.AddField(
            model_name='car',
            name='owner_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد مالک قبلی'),
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='cars', to='core.feature', verbose_name='امکانات و آپشن\u200cها'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='آدرس سئو (slug)')),
                ('summary', models.TextField(blank=True, verbose_name='خلاصه کوتاه (متن لیست)')),
                ('content', models.TextField(verbose_name='متن کامل مقاله')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='عکس شاخص')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.category', verbose_name='دسته\u200cبندی')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='core.tag', verbose_name='تگ\u200cها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ('-created_at',),
            },
        ),
    ]
