# Generated by Django 5.2.8 on 2025-11-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_feature_tag_car_has_accident_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان انتشار'),
        ),
        migrations.AddField(
            model_name='article',
            name='reading_time',
            field=models.PositiveIntegerField(blank=True, help_text='در صورت خالی بودن، به صورت خودکار از روی متن محاسبه می\u200cشود.', null=True, verbose_name='زمان مطالعه (دقیقه)'),
        ),
    ]
