# Generated by Django 5.2.8 on 2025-11-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_inspection_done',
            field=models.BooleanField(default=False, verbose_name='کارشناسی بدنه: انجام شده'),
        ),
        migrations.AddField(
            model_name='car',
            name='technical_inspection_done',
            field=models.BooleanField(default=False, verbose_name='کارشناسی فنی: انجام شده'),
        ),
        migrations.AddField(
            model_name='car',
            name='written_report_available',
            field=models.BooleanField(default=False, verbose_name='گزارش کتبی کارشناسی: قابل ارائه'),
        ),
    ]
