# Generated by Django 5.2.8 on 2025-11-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_car_body_inspection_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cars', to='core.tag', verbose_name='تگ\u200cها'),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_inspection_done',
            field=models.BooleanField(default=False, verbose_name='کارشناسی بدنه'),
        ),
        migrations.AlterField(
            model_name='car',
            name='technical_inspection_done',
            field=models.BooleanField(default=False, verbose_name='کارشناسی فنی'),
        ),
        migrations.AlterField(
            model_name='car',
            name='written_report_available',
            field=models.BooleanField(default=False, verbose_name='گزارش کتبی کارشناسی'),
        ),
    ]
