# Generated by Django 5.2.8 on 2025-11-24 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_car_tags_alter_car_body_inspection_done_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/', verbose_name='عکس')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین (alt)')),
                ('is_primary', models.BooleanField(default=False, verbose_name='استفاده به\u200cعنوان تصویر اصلی؟')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.car', verbose_name='خودرو')),
            ],
            options={
                'verbose_name': 'عکس خودرو',
                'verbose_name_plural': 'گالری عکس خودرو',
                'ordering': ('ordering', 'id'),
            },
        ),
    ]
