# Generated by Django 5.2.8 on 2025-11-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('car', 'خودرو'), ('article', 'مقاله')], default='car', max_length=20, verbose_name='نوع تگ'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tag_type': 'article'}, related_name='articles', to='core.tag', verbose_name='تگ\u200cها'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'tag_type': 'car'}, related_name='cars', to='core.tag', verbose_name='تگ\u200cها'),
        ),
    ]
