# Generated by Django 5.2.8 on 2025-11-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_tag_tag_type_alter_article_tags_alter_car_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام و نام خانوادگی"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="شماره تماس")),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("buy", "خرید خودرو"),
                            ("sell", "فروش خودرو"),
                            ("stock", "سوال درباره موجودی"),
                            ("feedback", "پیشنهاد یا انتقاد"),
                        ],
                        max_length=20,
                        verbose_name="موضوع",
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="شهر"),
                ),
                ("message", models.TextField(verbose_name="متن پیام")),
                (
                    "notify_me",
                    models.BooleanField(
                        default=False,
                        verbose_name="اطلاع\u200cرسانی درباره خودروهای مشابه",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ارسال"),
                ),
            ],
            options={
                "verbose_name": "پیام تماس",
                "verbose_name_plural": "پیام\u200cهای تماس",
                "ordering": ("-created_at",),
            },
        ),
    ]
